#!/usr/bin/env -vS podman --runtime runc --storage-driver vfs --cgroup-manager cgroupfs --events-backend file build --build-arg PARAMETER=${PARAMETER} -t local/build-enchive${PARAMETER}:latest . -f
ARG PARAMETER
FROM local/devuan-4-build-base${PARAMETER}:latest
RUN \
  export PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin && hash -r && set -x && \
  \
  sys build pre && \
  sys build depend git ca-certificates make gcc libc6-dev && \
  source $(which sys) build env && \
  source $(which sys) build clone skeeto/enchive && \
  sed -i -e "s,/dev/tty,/bin/false/skip," src/enchive.c && \
  make CFLAGS=" -DENCHIVE_AGENT_DEFAULT_ENABLED=0 -DENCHIVE_OPTION_AGENT=0 ${CFLAGS} " install && \
  exec sys build post
