#!/usr/bin/env -vS podman --runtime runc --storage-driver vfs --cgroup-manager cgroupfs --events-backend file build --build-arg PARAMETER=${PARAMETER} -t local/build-rdup${PARAMETER}:latest . -f
ARG PARAMETER
FROM local/devuan-4-build-base${PARAMETER}:latest
RUN \
  export PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin && hash -r && set -x && \
  \
  sys build pre && \
  sys build depend git ca-certificates autoconf make automake libtool pkgconf libglib2.0-dev libarchive-dev nettle-dev && \
  source $(which sys) build env && \
  source $(which sys) build clone miekg/rdup && \
  autoreconf && \
  ./configure --enable-debug && \
  sed -i -e '/^CFLAGS=/s,$, -Wno-error -mtune=generic,' GNUmakefile && \
  make && \
  make install && \
  exec sys build post
