#!/usr/bin/env -vS podman --runtime runc --storage-driver vfs --cgroup-manager cgroupfs --events-backend file build --build-arg PARAMETER=${PARAMETER} -t local/build-rsbep-backup${PARAMETER}:latest . -f
ARG PARAMETER
FROM local/devuan-4-build-base${PARAMETER}:latest
RUN \
  export PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin && hash -r && set -x && \
  \
  sys build pre && \
  sys build depend git ca-certificates autoconf automake gcc make libc6-dev && \
  source $(which sys) build env && \
  source $(which sys) build clone ttsiodras/rsbep-backup && \
  aclocal && \
  ./configure && \
  make && \
  make install && \
  exec sys build post
