#!/usr/bin/env -vS podman --runtime runc --storage-driver vfs --cgroup-manager cgroupfs --events-backend file build --build-arg PARAMETER=${PARAMETER} -t local/build-base91${PARAMETER}:latest . -f
ARG PARAMETER
FROM local/devuan-4-build-base${PARAMETER}:latest
RUN \
  export PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin && hash -r && set -x && \
  \
  sys build pre && \
  sys build depend git ca-certificates make gcc libc6-dev wget && \
  source $(which sys) build env && \
  cd /usr/local/src && \
  wget http://downloads.sourceforge.net/base91/base91-0.6.0.tar.gz && \
  tar xzpkf base91-*.tar.gz && \
  cd base91-0.6.0/ && \
  make && \
  make install && \
  exec sys build post
