#!/usr/bin/env -vS podman --runtime runc --storage-driver vfs --cgroup-manager cgroupfs --events-backend file build --build-arg PARAMETER=${PARAMETER} -t local/build-criu${PARAMETER}:latest . -f
ARG PARAMETER
FROM local/devuan-4-build-base${PARAMETER}:latest
RUN \
  export PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin && hash -r && set -x && \
  \
  sys build pre && \
  sys build depend git ca-certificates make gcc libc6-dev protobuf-c-compiler git libbsd-dev pkgconf libprotobuf-c-dev libnftables-dev libgnutls28-dev python3 protobuf-compiler libprotobuf-dev libnet1-dev libnl-3-dev libcap-dev xmlto asciidoc-base python3-pip && \
  source $(which sys) build env && \
  source $(which sys) build clone checkpoint-restore/criu && \
  git checkout cd9680ce8935ba828ccdd59314442900c9699703 && \
  make && \
  make install && \
  exec sys build post
