#!/usr/bin/env -vS podman --runtime runc --storage-driver vfs --cgroup-manager cgroupfs --events-backend file build --build-arg PARAMETER=${PARAMETER} -t local/build-glza${PARAMETER}:latest . -f
ARG PARAMETER
FROM local/devuan-4-build-base${PARAMETER}:latest
RUN \
  export PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin && hash -r && set -x && \
  \
  sys build pre && \
  sys build depend make gcc libstdc++-10-dev git ca-certificates && \
  source $(which sys) build env && \
  source $(which sys) build clone Intensity/GLZA && \
  make && \
  cp -p -v ./GLZA /usr/local/bin/ && \
  exec sys build post
