#!/usr/bin/env -vS podman --runtime runc --storage-driver vfs --cgroup-manager cgroupfs --events-backend file build --build-arg PARAMETER=${PARAMETER} -t local/build-blockdiff${PARAMETER}:latest . -f
ARG PARAMETER
FROM local/devuan-4-build-base${PARAMETER}:latest
RUN \
  export PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin && hash -r && set -x && \
  \
  sys build pre && \
  sys build depend git ca-certificates make pandoc python3 && \
  source $(which sys) build env && \
  source $(which sys) build clone lengfeld/blockdiff && \
  make && \
  make tests && \
  make install install-doc prefix=usr/local && \
  exec sys build post
