#!/usr/bin/env -vS podman --runtime runc --storage-driver vfs --cgroup-manager cgroupfs --events-backend file build --build-arg PARAMETER=${PARAMETER} -t local/build-vdo${PARAMETER}:latest . -f
ARG PARAMETER
FROM local/devuan-4-build-base${PARAMETER}:latest
RUN \
  export PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin && hash -r && set -x && \
  \
  sys build pre && \
  sys build depend git ca-certificates gcc make libc6-dev uuid-dev zlib1g-dev libdevmapper-dev libblkid-dev && \
  source $(which sys) build env && \
  source $(which sys) build clone dm-vdo/vdo && \
  make bindir=/usr/local/bin mandir=/usr/local/share/man defaultdocdir=/usr/local/share/doc sysconfdir=/usr/local/etc && \
  make install bindir=/usr/local/bin mandir=/usr/local/share/man defaultdocdir=/usr/local/share/doc sysconfdir=/usr/local/etc && \
  exec sys build post
